extends Node

@warning_ignore_start("unused_signal")
signal score_changed(score: int)
signal wave_changed(wave: int)
signal energy_changed(player_id: String, energy: int)
signal plasma_collected(amount: float)
signal beam_charge_changed(player_id: String, current: float, maximum: float, overdrive_ready: bool)
signal player_motion_changed(player_id: String, vertical_intent: float)
signal player_died()
signal game_over_requested()
signal powerup_collected(upgrade)
signal upgrade_changed(player_id: String, effect: int, rank: int, max_rank: int)
signal upgrade_feedback_requested(player_id: String, text: String, capped: bool)
signal world_requested()
signal hiscore_requested()
signal start_screen_requested()
signal resume_requested()
signal restart_requested()
signal graphic_changed(level: String)
signal screen_shake_requested(strength: float, duration: float)
signal screen_flash_requested(color: Color, duration: float)
signal combo_changed(combo: int, multiplier: float, time_left: float)
signal score_popup_requested(points: int, combo: int, multiplier: float, world_position: Vector2)
@warning_ignore_restore("unused_signal")
